# Generated by Django 4.2.5 on 2023-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
